t3-oss/create-t3-turbo

README.md

Feel free to edit, ignore, or merge it 😄

docs: add EAS getting started guide

---

README.md

Figured this might be helpful for others after I spent an hour fighting with modules not resolving.
Tried to mirror the formatting of the docs best I could.

Include note about pnpm

---

packages/db/.gitignore
packages/db/index.ts
packages/db/prisma/schema.prisma
turbo.json

Generate prisma client outside of node modules, cache generated client

---

apps/expo/package.json
apps/expo/tailwind.config.cjs
apps/nextjs/package.json
apps/nextjs/postcss.config.cjs
apps/nextjs/tailwind.config.cjs
packages/config/tailwind-config/index.js
packages/config/tailwind-config/package.json
packages/config/tailwind-config/postcss.config.js
pnpm-lock.yaml
pnpm-workspace.yaml

feat: base preset for tailwind

---

turbo.json

Closes #58
cc @mattpocock 
Don't have time to look into this right now but if you find a solution feel free to submit a PR

fix: prisma cache lying

---

README.md

Previously, the screenshot said to use `npm install --prefix=../..` but this will throw an error in Vercel. After changing it to use `pnpm i -r`, the build step works properly!

Updated Vercel install command to use pnpm

---

packages/auth/package.json

the package.json in the auth package was pointing to the wrong index.ts

fix: point to right index.ts

---

apps/nextjs/package.json
pnpm-lock.yaml

installed the "wrong" dotenv lib in #100. hot patching to use the same as the db package

use dotenv-cli instead of dotenv

---

apps/nextjs/src/utils/api.ts

While checking out the repo I found a mistake that was made during [this commit](https://github.com/t3-oss/create-t3-turbo/tree/e64f6e5ea917b58b711dadda4c5f2878d2e0032c).

Fixed comment

---

apps/expo/src/screens/home.tsx
apps/nextjs/src/pages/index.tsx
packages/api/src/router/post.ts

This PR updates the following things regarding default app's home page:
- updates post styles so that it matches the style of `create-t3-app` default home page
- adds space between the post ID and "Selected post:" text
- adds "There are no posts" message instead of showing just the scrollbar when there are not posts
- adds an option to delete posts

feat: updated styles and added delete

---

.vscode/launch.json

This PR configures debugging on vscode and fixes #112.
Works for both the api routes, and the turborepo packages.

feat: configuring debugging on vscode

---

package.json
pnpm-lock.yaml

This PR fixes the lint script. Related issue: https://github.com/t3-oss/create-t3-turbo/issues/118

Fix lint script

---

README.md
apps/expo/app/index.tsx
apps/expo/app/post/[id].tsx
apps/nextjs/src/pages/index.tsx
packages/api/src/router/post.ts
packages/api/src/trpc.ts

- uses `useSearchParams` instead of manually retrieving them
- changes page name
- adds note to readme about expo router

feat: expo router improvements and post fields required

---

packages/env/package.json
pnpm-lock.yaml

Hi,
I found this missing when I tried to use this branch.
Thanks for this template.

add tsup dev dep to env package

---

README.md

Adds a note about turbo's new command

feat: add new init method with command to readme

---

apps/expo/eas.json

pin node version in eas.json

---

README.md
packages/db/drizzle.config.ts
packages/db/index.ts
packages/db/package.json
packages/db/schema/post.ts
packages/db/tsconfig.json
pnpm-lock.yaml

- Setup ESLint for `@acme/db` package now that we'll be working primarily with TypeScript having switched to Drizzle
- Update `@acme/db` `tsconfig.json` to include new Drizzle files
- Format `@acme/db` files with newly configured rules
- Format `README.md` and make some minor improvements

Configure ESLint for `db` Package, Format Files, Minor Tweaks

---

.env.example

fix: compatible database url in example env

---

packages/db/package.json

Add the `dev` script to `db` workspace.
This PR solves #628

fix(packaging): add `dev` script

---

apps/nextjs/package.json
apps/nextjs/src/app/layout.tsx
packages/auth/package.json
pnpm-lock.yaml
tooling/eslint/package.json

chore: note about dynamic

---

apps/expo/package.json
pnpm-lock.yaml

chore: bump expo

---

apps/expo/babel.config.js
apps/expo/metro.config.js
apps/expo/package.json
apps/expo/src/app/_layout.tsx
apps/expo/src/app/index.tsx
apps/expo/src/styles.css
apps/expo/src/types/nativewind-env.d.ts
apps/expo/tailwind.config.ts
apps/nextjs/postcss.config.cjs
pnpm-lock.yaml
tooling/tailwind/package.json
tooling/tailwind/postcss.js

https://github.com/marklawlor/nativewind/issues/600
https://www.nativewind.dev/v4/overview/

nativewind v4

---

apps/expo/package.json
apps/expo/tsconfig.json
tooling/typescript/base.json

Updated to match recommendations in: https://www.totaltypescript.com/tsconfig-cheat-sheet

Update base tsconfig.json

---

README.md

This pull request updates the Next.js version in the README from 13 to 14.

Update Next.js version in README

---

apps/nextjs/src/env.mjs

fix. cannot load environment variables

---

.vscode/settings.json
apps/expo/src/app/index.tsx
apps/nextjs/src/app/_components/posts.tsx

This PR addresses the issue of deprecated code in `app/index.tsx` and `_components/posts.tsx`.
The update involve a refactor from `api.useContext` to `api.useUtils` -> [docs](https://trpc.io/docs/client/react/useUtils).
These changes ensure compatibility with the latest version of `TRPc`.

Fix Deprecated code

---

packages/api/src/router/post.ts

Limit fetched posts

---

packages/db/index.ts

use planetscale connect instead of Client to allow additional configuration

Use planetscale `connect` instead of `Client` to allow additional configuration

---

tooling/eslint/nextjs.js

chore: Switched to a stricter set of eslint rules for next.js

---

apps/expo/package.json
apps/nextjs/package.json
packages/api/package.json
pnpm-lock.yaml

Testing https://github.com/trpc/trpc/pull/5270

chore: bump trpc

---

.github/workflows/ci.yml

chore(CI): Allow cancel in progress only Branch name isn't main

---

README.md

I found some typos in the root README.md file. Hope you agree with them, looking forward to merge this.

fix(docs): clean up some typos in README.md

---

apps/expo/app.config.ts

- Allow for merging config files when `app.json` is also present

feat: allow for merging `app.json` config file

---

apps/expo/metro.config.js

fix: Metro config

---

package.json
pnpm-lock.yaml
tooling/eslint/package.json

chore: turbo@1.13.2

---

packages/db/src/index.ts

fix(db): Export sql and aggregation functions

---

apps/auth-proxy/package.json
apps/expo/package.json
apps/nextjs/package.json
package.json
packages/api/package.json
packages/auth/package.json
packages/db/package.json
packages/ui/package.json
packages/validators/package.json
pnpm-lock.yaml
tooling/eslint/package.json
tooling/prettier/package.json
tooling/tailwind/package.json

next 14.2
trpc rc #977
ts 5.4.5
react monoreop #983

chore: dep bumps

---

apps/nextjs/eslint.config.js
apps/nextjs/src/app/layout.tsx
apps/nextjs/src/env.ts
apps/nextjs/src/trpc/react.tsx
packages/auth/env.ts
packages/auth/eslint.config.js
packages/auth/src/config.ts
tooling/eslint/base.js

x-ref: https://x.com/mattpocockuk/status/1782333031518220643

feat: add no-restricted-properties

---

.env.example
README.md
apps/auth-proxy/package.json
apps/expo/src/app/post/[id].tsx
apps/nextjs/src/env.ts
packages/api/src/router/post.ts
packages/auth/package.json
packages/db/package.json
packages/db/src/config.ts
packages/db/src/index.ts
packages/db/src/schema/_table.ts
packages/db/src/schema/auth.ts
packages/db/src/schema/post.ts
pnpm-lock.yaml

refactor: use planetscale -> supabase

---

apps/nextjs/src/app/page.tsx
packages/auth/env.ts
packages/auth/src/config.ts

fix: auth trust host only in dev

---

apps/expo/metro.config.js

Add explicit metro configuration for exports
