t3-oss/create-t3-turbo

- README.md
Since it wasn't that evident, and "turbo" in the name can refer to many other things these days, from React Native TurboModules to Hotwire Turbo (and the associated react-native-turbo).
> Add info about Turborepo to README

- README.md
Currently, anyone that enters this project will have to search nexpo docs to understand how to change the default behavior of a fresh project that uses `create-t3-turbo`. This PR creates a bit more context on how to do this, and links to the official docs. Any feedback is appreciated.
Preview is available at https://github.com/minsk-dev/create-t3-turbo/tree/docs/other-sources.
> Adds information about how to use `web`, `iOS` and `android`

- packages/db/package.json
Both Android Studio and Prisma run on port: 5555 by default, so I assigned Prisma Studio to run on 5556 to avoid conflict.
Originally suggested 5000 but changed to 5556 due to a known issue of port 5000 not being available on some Macs.
> Prisma studio new port

- apps/expo/metro.config.js
There are two things here:
1. The Expo defaults for Metro were overwritten with `module.exports = { (new object) };`. It's better to use the `expo/metro-config` and change the config object from `getDefaultConfig`. This includes the defaults we carefully put together to get the most out of Metro and helps you safe guard against future big Metro changes.
2. Metro wasn't configured for monorepo usage, which likely leads to unexpected errors later on. With this config, you should be able to use pretty much any package manager or monorepo tool. ([like pnpm with turborepo](https://github.com/byCedric/expo-monorepo-example#readme) 😄)
> fix: use Expo default metro config and configure monorepo

- apps/expo/index.ts
- apps/expo/package.json
- apps/expo/src/_app.tsx
this is a fix for the issue i was having in #31 
it seems that the entry point for expo needs to be index.*
so i've renamed and moved the file up out of the src folder into the root.
`npx expo run:ios` now works, notice the index.tsx loading bar, this was not there previously as index was not found...
now we are getting the expected localhost error
> fix: rename expo entry file

- .github/workflows/ci.yml
- package.json
- packages/db/package.json
- turbo.json
Dont `prisma generate` on postinstall, but instead make build/dev depend on it.
Ref: https://twitter.com/mattpocockuk/status/1582660272330018816
> fix: make build/dev depend on db-generate

- packages/db/.gitignore
- packages/db/index.ts
- packages/db/prisma/schema.prisma
- turbo.json
Reverts t3-oss/create-t3-turbo#37
Because https://github.com/t3-oss/create-t3-turbo/issues/42
> Revert "Generate prisma client outside of node modules, cache generated client"

- packages/db/index.ts
After running into issues with the prisma client creating multiple connections, I did some digging and found that it's a [common problem with next](https://www.prisma.io/docs/guides/database/troubleshooting-orm/help-articles/nextjs-prisma-client-dev-practices). 
This PR uses a section of code from [this issue](https://github.com/prisma/prisma/issues/5007#issuecomment-740803749) to resolve the problem by preventing the client from being recreated.
Quick note: I didn't clone this repo when starting my project, I followed the article on migrating an existing t3 app. If there is already a fix for this somewhere that I missed, my bad.
> Prevent creation of multiple prisma clients

- .npmrc
- packages/db/index.ts
- turbo.json
This PR addresses the error `warn(prisma-client) There are already 10 instances of Prisma Client actively running` when adding Prisma to Next.js, as recommeded by Prisma on https://www.prisma.io/docs/guides/database/troubleshooting-orm/help-articles/nextjs-prisma-client-dev-practices.
Additionally, I've been able to restore turbo caching to the `generate-db` script from `packages/db` and hoist the generated artifacts from the client to the root of the project. This seems to solve the problem found with Next, where it doesn't play well with non-node_module dirs.
To reproduce and test caching behavior for the Prisma Client and applications:
1. Clone the repo and install the dependencies.
2. Run the `build` script on the root of the project. It should both generate the client, and build the …
> Enable Prisma Client caching by Turbo and hoist Client artifacts

- apps/nextjs/next.config.mjs
- apps/nextjs/src/pages/_app.tsx
- apps/nextjs/src/pages/index.tsx
- apps/nextjs/tsconfig.json
- packages/api/src/router/auth.ts
- packages/api/src/router/index.ts
- packages/api/tsconfig.json
Integrates #36
- Fix `nextjs` compilation error by adding `@acme/auth` to the list of nextjs transpiled modules
- Add typescript validation to next-auth `Session` augmented type in packages other than `@acme/auth`
- Add Auth example in nextjs web app
> Fix `auth` branch errors

- packages/db/index.ts
This allows accessing the types generated by prisma in other packages.
> Export prisma/client from db to expose types to other packages

- packages/db/package.json
Currently, the `dev` script `pnpm with-env prisma studio --port 5556` does not open prisma studio to port 5556. This is because `dotenv-cli` requires a `--` to distinguish between flags passed to dotenv and flags passed to the underlying command ([see docs](https://github.com/entropitor/dotenv-cli#flags-to-the-underlying-command)).
Adding a `--` to the end of the `with-env` script solves this.
**Alternative solution**:
We could move `--` to the individual scripts using `with-env` rather than within the `with-env` script itself.
Example: `pnpm with-env -- prisma studio --port 5556`
> fix: add -- to pass flags to underlying command

- apps/expo/src/screens/home.tsx
SafeAreaView imported from react native is not working on Android. The correct is to import it from react-native-safe-area-context.
> Fix SafeAreaView import to work correctly on Android

- .github/workflows/ci.yml
Use environment variable to skip validations on `CI.yml` workflow, or is there a reason to validate env schema there?
> feat(ci): skip nextjs env validation

- .github/workflows/ci.yml
- apps/expo/app.json
- apps/expo/eas.json
- apps/expo/package.json
- package.json
- patches/react-native@0.70.5.patch
- pnpm-lock.yaml
Closes #99
Caused by Expo SDK 47 apparently not supporting monorepos...
This was fixed in the latest react-native@0.71-rc.5 although I got a new error there (coming from react-native-safe-area-context) so decided to just revert to supported version and patch the package...
> fix: expo eas build

- apps/expo/expo-plugins/with-modify-gradle.js
Forgot to check if the lines were appended while writing the plugin, so here's the fix that will not allow them to be inserted multiple times.
> fix: check if lines are already appended in the expo plugin

- packages/api/src/trpc.ts
Rather than checking that `session` exists AND `session.user` exists. Simply check that `session?.user` exists.
> Use optional chaining

- apps/expo/eas.json
Fixes `InvalidEasJsonError: eas.json is not valid.` error when running `eas build` with an eas-cli version < 3.3.0.
`build.preview.ios.resourceClass` is only supported in eas-cli >= 3.3.0
> expo-cli 3.3.0

- README.md
- apps/expo/src/utils/api.tsx
**Why?**
I recently tested out how easy it would be to go from a bootstrapped template to a deployed application in Testflight. I discovered that the Expo app needs a deployed server in order to communicate with the tRPC backend logic (of course 🤦🏼‍♂️).
I felt that this was not clearly stated in the documentation, so here are my two cents. I'm of course open to any proposed changes ☺️
> docs: update `api` util and README

- .github/workflows/ci.yml
- package.json
Now that Expo SDK was upgraded to v48 it supports React 18.2, meaning the `manypkg check` can be re-enabled in CI.
In addition, running `manypkg check` resulted in an error so `manypkg fix` sorted the relevant imports.
> fix: re-enable manypkg in CI

- apps/expo/eas.json
- I configured both `development` and `production` builds to make use of M1 workers; they were previously only configured for `preview` builds. [Expo says](https://blog.expo.dev/m1-workers-on-eas-build-dcaa2c1333ad) that M1 workers generally speed up builds, and will be the default before Q2 2023.
- I indented the `eas.json` file and arranged the json properties alphabetically for better readability.
> Configure EAS Builds to Use M1 Workers

- renovate.json
This should stop the "Renovate failed to look up the following dependencies" warnings for acme packages
> fix(renovate): don't run renovate on acme

- package.json
- pnpm-lock.yaml
- prettier.config.js
prettier-plugin-tailwindcss now works with @ianvs/prettier-plugin-sort-imports so changing back to it
Fixes #181
> fix(prettier): @ianvs/prettier-plugin-sort-imports now works with prettier-plugin-tailwindcss

- .eslintrc.js
- LICENSE
- apps/expo/app.config.ts
- apps/expo/app/post/[id].tsx
- apps/expo/package.json
- apps/expo/src/types/nativewind.d.ts
- apps/expo/src/utils/api.tsx
- apps/expo/tsconfig.json
- apps/nextjs/package.json
- apps/nextjs/src/pages/api/auth/[...nextauth].ts
- apps/nextjs/src/pages/api/trpc/[trpc].ts
- apps/nextjs/src/utils/api.ts
- package.json
- packages/api/index.ts
- packages/api/package.json
- packages/api/src/router/post.ts
- packages/api/src/trpc.ts
- packages/api/transformer.ts
- packages/auth/package.json
- packages/auth/src/auth-options.ts
- packages/db/package.json
- pnpm-lock.yaml
- prettier.config.cjs
Closes #164
Makes `@acme/api` a dev dependency in `@acme/expo` since we only need the types and don't want to worry about leaking server code.
Also some other general maintenance work
> refactor: make acme/api devDep in expo

- apps/expo/package.json
- apps/nextjs/package.json
- package.json
I just noticed that the clean scripts are using `rm -rf`, which doesn't work on Windows machines. I know, it's probably not the best dev OS, but lots of people are using Windows :)
There are other ways to achieve this, but I found that this is one of the cleanest ways. It does assume that people use git, but even windows users _should_ be using git.
> fix: make clean scripts compatible with windows

- README.md
Current instructions aren't the most specific. See https://github.com/t3-oss/create-t3-turbo/issues/94.
> docs: Add manual expo start instructions to README.md

- .eslintrc.js
- apps/expo/package.json
- apps/nextjs/package.json
- package.json
- packages/api/package.json
- packages/auth/package.json
- packages/config/eslint/package.json
- pnpm-lock.yaml
- renovate.json
Rename eslint-config-acme to @acme/eslint-config, to match the naming convention of the repo. I have tested that linting works as intended.
> Rename eslint-config-acme to match the other packages

- renovate.json
See the discussion on #214 
This will keep tell Renovate to keep NPM dependencies more up to date.  As well as updating the `package.json` ranges in the process.
> update renovate to keep deps more up to date

- .gitignore
Updating the path of prisma db in `.gitignore` so it's more generic and properly ignores the databases
> fix: update gitignore, database not being ignored

- apps/expo/package.json
Brings back the `type-check` script as the expo router issue got fixed (see https://github.com/t3-oss/create-t3-turbo/issues/185#issuecomment-1493038578)
> fix: bring back `type-check` script

- apps/expo/eas.json
`m1-medium` has been deprecated. `m-medium` is now the preference.  See https://docs.expo.dev/build-reference/eas-json/#ios-specific-options
I found this creating a build.  `eas` show this warning:
```bash
$ eas build --profile preview --platform ios
Resource class m1-medium is deprecated. Use m-medium instead.
```
> update eas-expo build resource class

- packages/db/index.ts
Switch to a slightly more "honest" cast of `globalThis` in the db index file.
`globalThis` _is_ an object which has an optional `prisma` property - it doesn't make much difference in this case but casting to `as unknown` allows making a slightly more unsafe cast, which isn't needed here - at least I don't think it is.
> Simplify `as unknown as ...` cast in db/index.ts

- apps/expo/src/utils/api.tsx
Turns out when just using expo go and local development what was originally here works fine.  But if you end up building your own dev client (https://docs.expo.dev/develop/development-builds/introduction/#what-is-an-expo-dev-client) then `manifest` will no longer be around. Instead you need to use `manifest2`.
See description of `manifest` and `manifest2` here: https://docs.expo.dev/versions/latest/sdk/constants/#nativeconstants
> fix localhost determination during expo local dev

- apps/nextjs/src/env.mjs
- packages/auth/env.mjs
clone a new project a follow the installation guide.
Run pnpm run lint
Lint fails
lint fails on .env validation.
On `apps/nextjs/package.json` SKIP_ENV_VALIDATION is set but it is not checked in `createEnv`
This PR ads `SKIP_ENV_VALIDATION` to the `skipValidation` property on `createEnv`
> Skip env validation on lint

- README.md
- apps/nextjs/src/pages/_app.tsx
- package.json
- packages/api/src/trpc.ts
- pnpm-lock.yaml
- prettier.config.cjs
I upgraded the `prettier-plugin-sort-imports` package to `^4.0.2` and updated the prettier config to use updated options. Also ran formatting, which resulted in some small spacing/ordering updates. (For reference: https://github.com/IanVS/prettier-plugin-sort-imports/releases/tag/v4.0.0)
> Upgrade prettier-plugin-sort-imports package to v4

- packages/api/tsconfig.json
It seems that this got left around after the transformer.ts file got deleted.
> chore: remove old file from tsconfig's include

- turbo.json
A change to `tsconfig.json` should invalidate the cache of all child workspaces, it is the example Turbo [uses in its documentation of `globalDependencies`](https://turbo.build/repo/docs/core-concepts/caching/file-inputs#specifying-additional-inputs).
For example, adding a new type could create different results for the `type-check` job, updating `paths` could alter imports used by various jobs.
> add TypeScript config to Turborepo's global dependencies

- apps/expo/src/app/index.tsx
- apps/expo/src/app/post/[id].tsx
- apps/expo/src/utils/api.tsx
- apps/nextjs/src/pages/index.tsx
- pnpm-lock.yaml
Remove React.FC usage in templates, replacing with standard function syntax as per Cje tweet https://twitter.com/ccccjjjjeeee/status/1668694515484336145
> chore: Replace React.FC with basic function syntax

- apps/expo/app.config.ts
Added `android.package` to Expo app config as it is needed for Android builds. Since `ios.identifier` is present, `android.package` should also be present.
> Add `android.package` to Expo app config

- packages/api/src/router/post.ts
I think the delete post endpoint should be protected. 
It would also serve as a better example for the example.
> fix(api): Make delete post endpoint protected

- packages/db/schema/auth.ts
Updating the data type to `text` fixes the Google Provider issue
This is also how it is configured in the next auth [prisma adapter](https://authjs.dev/reference/adapter/prisma#create-the-prisma-schema-from-scratch) with the following note for MySQL:
> When using the MySQL connector for Prisma, the [Prisma String type](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#string) gets mapped to varchar(191) which may not be long enough to store fields such as id_token in the Account model. This can be avoided by explicitly using the Text type with @db.Text.
fixes #585
> Update id_token data type to work with Google Provider

- packages/db/schema/auth.ts
Otherwise Drizzle cannot infer the type of session.user (or t3turbo_session.user).
This error also prevents the programmer from being able to access Drizzle studio
> Specify foreign key for sessionsRelations

- .github/workflows/ci.yml
- package.json
Run `manypkg check` on `postinstall` to catch dependency issues as early as possible and not only in ci.
Also removed `Check workspaces` step from ci workflow since check runs after `pnpm install` with this change.
> run manypkg check postinstall

- README.md
Glad Solito is on the FAQ here. I changed the wording slightly – the existing wording made it sound like *you can't use Solito with T3*. Reading the paragraph would clarify that missed assumption, but I thought it would be best to update the heading.
Nice work.
> Update Solito wording

- turbo/generators/config.ts
- turbo/generators/templates/package.json.hbs
The turbo generator still uses `manypkg` package. The pacakge was removed in PR #717 
Migrate used `manypkg` command to `sherif`.
If you create a new package the command throws an error because of the the [rules](https://www.npmjs.com/package/sherif#rules) integrated in sherif and used package versions in the workspaces.
Sample output:
```
❯ pnpm turbo gen init
>>> Modify "create-t3-turbo" using custom generators
? What is the name of the package? (You can skip the `@acme/` prefix) test
? Enter a space separated list of dependencies you would like to install
Packages: +2
++
Progress: resolved 7, reused 2, downloaded 0, added 2, done
1 issue found in ./packages/test/package.json:
✓ fixed package.json should not have empty dependencies fields. empty-dependencies
│ {
-   "dependencies": {} …
```
> fix: turbo generator still used manypkg

- apps/expo/src/utils/api.tsx
The logger is an important feature of TRPC, especially in RN since the network inspector isn't that great so it's nice to have correct defaults. It can be disabled at anytime.
The loggerLink uses CSS mode by default which breaks some log messages in react native.
This PR addresses this issue.
Mentioned in https://github.com/trpc/trpc/issues/2898
enabled check is taken from the official t3 stack [template](https://github.com/t3-oss/create-t3-app/blob/9eac8f5cb220b00261e4151e596ba7efa3e398b5/cli/template/extras/src/utils/api.ts#L38C14-L38C14).
> implement react native compatible logger

- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/workflows/ci.yml
- .vscode/extensions.json
- .vscode/settings.json
- apps/expo/package.json
- apps/expo/src/app/_layout.tsx
- apps/expo/src/app/index.tsx
- apps/expo/src/utils/api.tsx
- apps/nextjs/next.config.js
- apps/nextjs/package.json
- apps/nextjs/src/env.js
- apps/nextjs/tsconfig.json
- package.json
- packages/api/package.json
- packages/auth/package.json
- packages/db/package.json
- packages/db/src/schema/_table.ts
- pnpm-lock.yaml
- tooling/eslint/base.js
- tooling/eslint/package.json
- tooling/prettier/index.js
- tooling/tailwind/package.json
- turbo/generators/templates/package.json.hbs
This is a "polish up" PR. I've split it into two commits to ease code review, and to ensure if changes are requested it won't block the entire PR.
Changes in 1st Commit:
- Organize variables and scripts across packages alphabetically
- Replace broken link in `.github/ISSUE_TEMPLATE/feature_request.yml`
- Edit the `typecheck` job in `.github/workflows/ci.yml` to have pnpm running it instead of turbo
- Minor formatting improvements
Changes in 2nd Commit:
- Add `prettier` to the `eslint` package; it currently doesn't have it installed
- Remove unnecessary `React` import from `apps/expo/src/app/_layout.tsx`
- Standardize function format across `expo` app
- Import `useState` instead of the whole `React` object
- Organize recommended extensions so they appear in the Extensions Tab in …
> Polish PR: Minor Refactoring & Formatting Improvements

- packages/db/src/schema/auth.ts
Fixes the issue
``` 
@acme/nextjs:dev: [auth][cause]: Error: Data too long for column 'access_token' at row 1
```
----
got this error while testing with azure ad - Now `id_token` and `access_token` have the same column type.
> fix: wrong column type for access_token

- packages/db/src/schema/auth.ts
Fixes the following deprecation warning:
```
@deprecated — : Please use primaryKey({ columns: [] }) instead of this function
```
Ref: https://github.com/drizzle-team/drizzle-orm/releases/tag/0.29.0
> fix: update compoundKey to fix deprecation message

- apps/nextjs/src/app/_components/posts.tsx
- apps/nextjs/src/app/layout.tsx
- apps/nextjs/src/app/page.tsx
- apps/nextjs/src/trpc/react.tsx
- packages/api/src/router/post.ts
Mimics https://github.com/t3-oss/create-t3-app/pull/1723
> chore: don't pass headers to cc

- .npmrc
This PR reverts the removal of the .npmrc file because eas-cli doesn't play well with pnpm yet.
See more at https://github.com/t3-oss/create-t3-turbo/issues/867
Tried public-hoist-pattern with expo and eas-cli, but the eas build command still fails because it cannot locate the metro config, a dead end.
> fix(expo): Revert `node-linker=hoisted` change

- turbo/generators/templates/package.json.hbs
> fix: typo in eslint version

- .gitignore
Since the newest changes with `tsc` in this repo, `/dist` is not just about expo anymore. I couldn't decide between "production" and "typescript" categories. Would like your opinion.
> Change `/dist` category in `.gitignore`

- apps/nextjs/src/app/api/auth/[...nextauth]/route.ts
I was having problems where it was fetching a completely unrelated cookie that was not the one we were looking for. This fixes the problem and makes it more reliable
> Use .find() instead of always first cookie

- packages/ui/package.json
The shadcn also contains ui files with the .ts extension, such as use-toast.ts.
An error shows if ".ts" is not added.
> add .ts to the list of shadcn ui exports

- .github/renovate.json
Update the `renovate.json` file to extend the files matched by the npm module to include `package.json.hbs` by following https://docs.renovatebot.com/modules/manager/#file-matching
Note that I have not tested this since I don't have renovate set up on my fork, but since the `package.json.hbs` file is a valid `package.json` file I believe this should work.
> feat: get renovate to update .hbs file

- tooling/prettier/index.js
Fixes #1052 by adding overrides to use JSON and babel parsers for `*.json.hbs` and `*.js.hbs` files. If this is too complex of a solution we can simply ignore the files from prettier
> feat: use parsers for .hbs files

- tooling/github/setup/action.yml
I was getting the following warnings in my project's GitHub Actions:
I traced it to `pnpm/action-setup` which currently is set to v2 but the [documentation](https://github.com/marketplace/actions/setup-pnpm) show v4 as the latest.
> Update pnpm/action-setup from v2 to v4

- .vscode/settings.json
When I was fixing conflict in `pnpm-lock.yaml` it got formatted unnecessarily. By default extension ignores files from `.prettierignore`, but we use gitignore.
> VSC Prettier extension: ignore files from .gitignore

- packages/api/package.json
- packages/auth/tsconfig.json
- packages/db/package.json
- packages/db/tsconfig.json
- packages/ui/package.json
- packages/ui/tsconfig.json
- packages/validators/package.json
- packages/validators/tsconfig.json
- tooling/typescript/base.json
- tooling/typescript/internal-package.json
- turbo.json
- turbo/generators/templates/package.json.hbs
- turbo/generators/templates/tsconfig.json.hbs
less watchers should be more "easy" on the dev machine running them :)
- is there some way to not have to duplicate `build` and `dev` scripts?
> chore: use `turbo watch` instead of `tsc --watch`

- apps/expo/index.ts
- apps/expo/package.json
This PR is for the problem of not finding the correct path for the expo-router on android devices when using monorepo.
> fix: expo router main file

- apps/expo/eas.json
The current EAS build environment uses Node.js v18.16.1 and pnpm v9.3.0. However, this monorepo now utilizes pnpm's catalog feature, which was [introduced in pnpm v9.5.0](https://pnpm.io/catalogs). 
Set pnpm to 9.6.0 to ensure catalog functionality support on EAS builds and Node.js version to match the one in the repo.
Relevant eas.json file [`apps/expo/eas.json`](https://github.com/t3-oss/create-t3-turbo/blob/main/apps/expo/eas.json#L7)
Screenshot of the error i recently encountered on eas:
> update eas build tools versions

- .npmrc
Since pnpm [v9](https://github.com/pnpm/pnpm/releases/tag/v9.0.0) was released [link-workspace-packages](https://pnpm.io/npmrc#link-workspace-packages) has been disabled by default. This means that if you were to run a command like:
`pnpm i @acme/validators -F @acme/auth-proxy`
it would fail with this error:
`@acme/validators is not in the npm registry, or you have no permission to fetch it.`.
Turning link-workspace-packages back on resolves this
> Enable link-workspace-packages in npmrc

- turbo/generators/templates/package.json.hbs
Since package default now emits declaration files by default we need to disable it on typecheck.
> fix: Add a flag to package gen typecheck script

- pnpm-lock.yaml
- tooling/eslint/package.json
This PR updates `typescript-eslint` from `8.1.0` to `8.3.0`.  Following the conversation in https://github.com/microsoft/vscode-eslint/issues/1911 I believe this would fix https://github.com/t3-oss/create-t3-turbo/issues/1155
> fix: update typescript-eslint to 8.3.0

- packages/auth/src/config.ts
The parameter "token", its value contains prefix "Bearer ". This will cause error.
> fix: slice token bearer prefix in invalidate function

- packages/auth/src/config.ts
- packages/ui/package.json
> update shadcn command to make sure it works

- tooling/github/setup/action.yml
Using this on my current setup, since it makes more sense. The .nvmrc file by default specifies 20.16, gh actions is using 20.17.
> feat: Update action.yml to use .nvmrc instead of hardcoded node version

- package.json
> fix: Continue executing `dev` when one task fails

- pnpm-lock.yaml
- tooling/eslint/package.json
- tooling/eslint/types.d.ts
Removes the need to manually type `@eslint/js` types by installing `@types/eslint__js` as a dev dependency for `@acme/eslint-config`.
Installing these types is also recommended in the `typescript-eslint` [getting started docs](https://typescript-eslint.io/getting-started/#step-1-installation).
> fix: add eslintjs types

- turbo.json
This PR enhances the dev script by adding a dependency on the `dev` task.
Before this change, if I edited something for example in the database schema, it would only trigger changes in `@acme/db`, and it would not trigger tsc for `@acme/api`. You would need to manually trigger it with another process (eg. `pnpm build -F @acme/api...`). Now, any changes to a package will correctly cascade down all tscs for packages that depend on it
> Improve dev script

- .vscode/launch.json
Once your project grows a lot, it gets increasingly harder to debug. Sometimes it doesn't work, sometimes it does.
This should improve the reliability of the debugger. (It worked for me on my "larger" repo)
> Make debugger more reliable

- apps/nextjs/next.config.js
- apps/nextjs/package.json
- pnpm-lock.yaml
Because of [Webpack's problems with ESM](https://github.com/unjs/jiti/issues/329) as far as I know.
> fix: Revert jiti to v1

- README.md
- apps/nextjs/src/app/api/auth/[...nextauth]/route.ts
- apps/nextjs/src/app/api/trpc/[trpc]/route.ts
- apps/nextjs/src/app/page.tsx
* Because of the bug described [here](https://github.com/vercel/next.js/issues/53562), I updated the line that exports runtime to check if the process is being run on Windows and select the nodejs runtime in that case.
* I also updated the README to explain this, since it could otherwise be confusing, and my changes should be removed if that bug is fixed.
* fixes #1280
> fix: disable edge runtime by default to enable windows development

- apps/expo/eas.json
The expo app's `eas.json` file specify `node` and `pnpm` versions that are incompatible with the engines specified in the root `package.json` file.
This is causing EAS builds to fail with the following error:
```
Running "pnpm install --no-frozen-lockfile" in /home/expo/workingdir/build directory
ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)
Your pnpm version is incompatible with "/home/expo/workingdir/build".
Expected version: ^9.14.2
Got: 9.7.0
This is happening because the package's manifest has an engines.pnpm field specified.
To fix this issue, install the required pnpm version globally.
To install the latest version of pnpm, run "pnpm i -g pnpm".
To check your pnpm version, run "pnpm -v".
Your Node version is incompatible with …
```
> fix: use correct node and pnpm versions in eas.json

- apps/expo/metro.config.js
We updated the domain for the Turborepo documentation, and am trying to make sure links get updated where I can find them.
Thanks for using Turborepo!
> Update Turborepo docs domain.
